[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.147.0"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/login/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200