[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/login/"
  status = 302
  force = true

[context.production]
  command = "hugo --gc --minify -b $URL"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_URL"