[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.121.0"  # Use your Hugo version

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200