[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# Primary redirect for root
[[redirects]]
  from = "/"
  to = "/login/"
  status = 302
  force = true

# Auth callback handling
[[redirects]]
  from = "/callback"
  to = "/login/"
  status = 200

# Handle all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "hugo --gc --minify -b $URL"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_URL"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"