[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.121.0"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/login/"
  status = 200
  force = true
  conditions = {Role = ["anonymous"]}

[[redirects]]
  from = "/"
  to = "/login/"
  status = 302
  force = true