[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.147.6"  # Use your Hugo version

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/login/"
  status = 302