[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.121.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/login/"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[context.production]
  command = "hugo --gc --minify"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_URL"