[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/login/"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/login/index.html"
  status = 200
  conditions = {Role = ["anonymous"]}

[context.production.environment]
  HUGO_BASEURL = "https://dulcet-fenglisu-848718.netlify.app/"